version: '3.1'

services:

  db:
    image: postgres:9.6.7-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - "~/dm/docker/postgresql/data:/var/lib/postgresql/data"
    ports:
      - 15432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - "~/dm/docker/pgadmin:/var/lib/pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.cm
      PGADMIN_DEFAULT_PASSWORD: 1234
      
  localstack:
    image: localstack/localstack
    restart: always
    ports:
      - "4567-4583:4567-4583"
      - "9000:8080"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
    volumes:
      - "~/dm/docker/localstack/data:/tmp/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
