sensu-server:
  image: ausdto/monitoring-stack
  ports:
    - "5672:5672"
    - "3000:3000"

gov-au-marketplace-api:
  build: .
  hostname: dm-api
  links:
    - sensu-server
  environment:
    - URL=https://dm-api.apps.platform.digital.gov.au/
    - API_TOKEN
